### PR TITLE
Penambahan nama kontributor

### PR DESCRIPTION
**Pull request by aprilianurafi**

### CODE REVIEW

**Comment by aprilianurafi** [comment]
> Penambahan nama kontributor

**Comment by Risnanda-K** [comment]
[Risnanda Kurniadi] (https://www.linkedin.com/in/risnanda-kurniadi-2a2284131)

**Comment by aprilianurafi** [comment]
[Aprillia_Nur_Afifah] (https://www.linkedin.com/mwlite/in/aprillia-nur-89a35b1a6)

**Comment by aprilianurafi** [comment]
[Aprillia_Nur_Afifah](https://www.linkedin.com/mwlite/in/aprillia-nur-89a35b1a6)

**Pull request merged**
